### ISSUE TITLE
Does it support 4800H?

### ISSUE THREAD

**Issue by hikaruchang** [AMD-OSX/bugtracker#107]
Does it support CPU 4800H?

**Comment by RightFS** [comment]
I think it does support 4800h

**Comment by HoshiYamazaki** [comment]
Yeah, the patches should work fine on 4800H, but have in mind that you got Ryzen CPU what has Vega inside, which is not supported by macOS so you will end without graphical acceleration.

**Comment by hikaruchang** [comment]
> Yeah, the patches should work fine on 4800H, but have in mind that you got Ryzen CPU what has Vega inside, which is not supported by macOS so you will end without graphical acceleration.

[EFI.zip](https://github.com/AMD-OSX/bugtracker/files/5581891/EFI.zip)
[opencore-2020-11-23-170925.txt](https://github.com/AMD-OSX/bugtracker/files/5581892/opencore-2020-11-23-170925.txt)

But I can't boot it. Can you help me?

**Comment by HoshiYamazaki** [comment]
> > Yeah, the patches should work fine on 4800H, but have in mind that you got Ryzen CPU what has Vega inside, which is not supported by macOS so you will end without graphical acceleration.
> 
> [EFI.zip](https://github.com/AMD-OSX/bugtracker/files/5581891/EFI.zip)
> [opencore-2020-11-23-170925.txt](https://github.com/AMD-OSX/bugtracker/files/5581892/opencore-2020-11-23-170925.txt)
> 
> But I can't boot it. Can you help me?

Ehh, you don't got the point. The system without graphical acceleration is only little better than running it in virtual machine, despite that you can get working power management via this kext:
https://github.com/trulyspinach/SMCAMDProcessor

I assume the battery life still will be worse than on windows, since the whole acceleration will be done via CPU (e.g. software rendering).

Install the Hackintosh when this adventure will be completed:
https://github.com/mvaisakh/Asus-X505ZA-Ryzen-Hackintosh/issues/1

And I don't have time to help, sorry.

**Comment by hikaruchang** [comment]
> mvaisakh / Asus-X505ZA-Ryzen-Hackintosh＃1

Thanks a lot!

**Comment by Uncatchable47** [comment]
> Yeah, the patches should work fine on 4800H, but have in mind that you got Ryzen CPU what has Vega inside, which is not supported by macOS so you will end without graphical acceleration.

Hey, could you sent the preview of yours config.plist file? I can't find any items and info other than here that is  possible to run macos on Ryzen 7 4800h

**Comment by alyxandraio** [comment]
@Rawen2344 We don't offer support for laptops because their GPUs aren't supported by macOS. If you really want to try, even though it will be nearly unusable, follow the AMD desktop config guide on Dortania.

**Comment by alkindivv** [comment]
> Does it support CPU 4800H? yes it does, but you won't get any graphics acceleration
